Repository ShailjaVerma18/Learning-Management-System-Nalanda-Open-University-, pull requests merged in 2025-09, with the labels that each got.

#82 implemented the admin analytics dashboard
  adminapp/adminappurls.py
  adminapp/analytics_utils.py
  adminapp/analytics_views.py
  adminapp/migrations/0002_branchstats_dailystats_programstats_studentactivity.py
  adminapp/models.py
  adminapp/templates/admin_dashboard.html
  adminapp/templates/adminhome.html
  adminapp/templates/adminparent.html
  requirements.txt
  studentapp/studentappurls.py
  studentapp/templates/viewmat.html
  studentapp/views.py
Labels: enhancement, GSSoC'25, Level 3

#83 Added Enhanced Code of Conduct: added badges, emojis, GIFs, contributor wall
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, Level 2, GSSoC'25

#87 Added back to top redirection in readme
  README.md
Labels: documentation, enhancement, Level 1, GSSoC'25

#121 Migrate database from SQLite to PostgreSQL for production deployment
  adminapp/migrations/0001_initial.py
  adminapp/migrations/0002_branchstats_dailystats_programstats_studentactivity.py
  adminapp/migrations/0003_newscategory_alter_news_table_newsannouncement.py
  adminapp/migrations/0004_normalize_database.py
  adminapp/migrations/0005_complete_normalization.py
  adminapp/migrations/0006_remove_newsannouncement_target_branches_and_more.py
  adminapp/models.py
  media/materials/2025/09/29/python.png
  nouapp/migrations/0001_initial.py
  nouapp/migrations/0002_alter_student_branch_alter_student_program_and_more.py
  nouapp/models.py
  nouproject/settings.py
  requirements.txt
  studentapp/migrations/0001_initial.py
  studentapp/migrations/0002_alter_sturesponse_branch_alter_sturesponse_program_and_more.py
  studentapp/models.py
Labels: enhancement, help wanted, GSSoC'25, Level 3, Infrastructure, Database, Backend, Scalability

#122 added back to top/bottom across all pages
  nouapp/templates/parent.html
Labels: enhancement, Level 2, GSSoC'25, Infrastructure, Frontend

#124 Enhanced Student and Admin Enquiry Management System
  adminapp/adminappurls.py
  adminapp/templates/admin_enquiry_dashboard.html
  adminapp/templates/admin_enquiry_detail.html
  adminapp/templates/adminparent.html
  adminapp/views.py
  nouapp/migrations/0001_initial.py
  nouapp/models.py
  studentapp/models.py
  studentapp/studentappurls.py
  studentapp/templates/create_enquiry.html
  studentapp/templates/enquiry_dashboard.html
  studentapp/templates/enquiry_detail.html
  studentapp/templates/studentparent.html
  studentapp/views.py
Labels: enhancement, GSSoC'25, Level 3, Frontend, Backend, UI/UX, Scalability
